server:
  port: 9091

spring:
  application:
    name: crawl

  rabbitmq:
    host: http://j9d203.p.ssafy.io
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev
  config:
    import: optional:configserver:http://j9d203.p.ssafy.io:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j9d203.p.ssafy.io:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"