server:
  port: 9999

spring:
  application:
    name: crawl

  rabbitmq:
    host: http://j9d203.p.ssafy.io
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev
  config:
    import: optional:configserver:http://j9d203.p.ssafy.io:8888