server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery_server:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 172.17.0.3
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web-service/**
          filters:
            - RewritePath=/web-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus