server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j9d203.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway
  rabbitmq:
    host: http://j9d203.p.ssafy.io
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: web
          uri: lb://WEB
          predicates:
            - Path=/web/**
          filters:
            - RewritePath=/web/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"