server:
  port: 9001

spring:
  application:
    name: gateway
  profiles:
    active: dev
  rabbitmq:
    host: http://j9d203.p.ssafy.io
    port: 5672
    username: guest
    password: guest
  config:
    import: optional:configserver:http://j9d203.p.ssafy.io:8888